apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-deployment
  labels:
    app: cat-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cat
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
      - name: cat
        image: janesee3/cat-application:1
        ports:
        - containerPort: 8080